---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
      description: Bearer токет который выдается после авторизации(есть как в заголовках
        ответа так и в json)
paths:
  "/api/cities":
    get:
      summary: list cities
      tags:
      - without Auth
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  cities:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        country_name:
                          type: string
  "/api/clubs":
    get:
      summary: List clubs
      tags:
      - without Auth
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  clubs:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        country_name:
                          type: string
                        city_name:
                          type: string
  "/api/countries":
    get:
      summary: list countries
      tags:
      - without Auth
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  countries:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
  "/api/user/signup":
    post:
      summary: register user
      tags:
      - User
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  token:
                    type: string
                  message:
                    type: string
                  user:
                    type: object
                    properties:
                      category:
                        type: string
                      city:
                        type: string
                      club:
                        type: string
                      country:
                        type: string
                      date_of_birth:
                        type: string
                      email:
                        type: string
                      email_verified:
                        type: boolean
                      gender:
                        type: string
                      id:
                        type: integer
                      name:
                        type: string
                      position:
                        type: string
                      rating:
                        type: string
                      surname:
                        type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    name:
                      type: string
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - name
                  - email
                  - password
              required:
              - user
  "/api/user/login":
    post:
      summary: login user
      tags:
      - User
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  token:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
              required:
              - user
  "/api/users":
    patch:
      summary: update user
      tags:
      - User
      security:
      - Bearer: {}
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    name:
                      type: string
                    email:
                      type: string
                    surname:
                      type: string
                    gender:
                      type: string
                    category:
                      type: string
                    rating:
                      type: string
                    position:
                      type: string
                    date_of_birth:
                      type: string
                    city_id:
                      type: integer
                    country_id:
                      type: integer
                    club_id:
                      type: integer
                  required: []
              required:
              - user
    get:
      summary: Get users list
      tags:
      - User
      security:
      - Bearer: {}
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        category:
                          type: string
                        city:
                          type: string
                        club:
                          type: string
                        country:
                          type: string
                        date_of_birth:
                          type: string
                        gender:
                          type: string
                        id:
                          type: integer
                        name:
                          type: string
                        position:
                          type: string
                        rating:
                          type: string
                        surname:
                          type: string
  "/api/user/logout":
    delete:
      summary: logout user
      tags:
      - User
      security:
      - Bearer: {}
      responses:
        '200':
          description: successful
  "/api/users/current_user":
    get:
      summary: Current user info
      tags:
      - User
      security:
      - Bearer: {}
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  user:
                    type: object
                    properties:
                      category:
                        type: string
                      city:
                        type: string
                      club:
                        type: string
                      country:
                        type: string
                      date_of_birth:
                        type: string
                      email:
                        type: string
                      email_verified:
                        type: boolean
                      gender:
                        type: string
                      id:
                        type: integer
                      name:
                        type: string
                      position:
                        type: string
                      rating:
                        type: string
                      surname:
                        type: string
servers:
- url: http://{defaultHost.default}
  variables:
    defaultHost:
      default: 172.16.4.220:4001
